import { Manrope, Sacramento } from "next/font/google";
import "../../global/css/main.css";
import Head from "next/head";


const manRope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
})

const sacramento = Sacramento({
  variable: "--font-sacramento",
  subsets: ["latin"],
  weight: ["400"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${manRope.variable} ${sacramento.variable}`}>
        { children }
      </body>
    </html>
  );
}
