import { Manrope, Outfit, Sacramento } from "next/font/google";
import "../../global/css/main.css";
import Head from "next/head";
import TopBar from "@/global/components/TopBar";
import NavBar from "@/global/components/NavBar";
import Footer from "@/global/components/Footer";


const manRope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
})

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={`${manRope.variable} ${outfit.variable}`}>
      <TopBar />
      <NavBar />
        { children }
        <Footer />
      </body>
    </html>
  );
}
