export const metadata = {
  title: 'Shopify Studio - Hack Your Shopify Store',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
      <>{children}</>

  )
}
