import Banner from "./_components/Banner"

export const metadata = {
    title: 'Shopify Packages | VYBE Marketing',
    description: 'Generated by Next.js',
  }
  
  export default function Layout({ children }) {
    return (
        <>
              <Banner />
              {children}</>
  
    )
  }
  