export const metadata = {
    title: 'Services.js',
    description: 'Generated by Next.js',
  }
  
  export default function Layout({ children }) {
    return (
        <>{children}</>
  
    )
  }
  