export const metadata = {
    title: 'Package.js',
    description: 'Generated by Next.js',
  }
  
  export default function Layout({ children }) {
    return (
     
        <>{children}</>
    )
  }
  